### PR TITLE
Support additional functional impact columns in Genome Nexus

### PR DESCRIPTION
**Pull request by ao508**
Add sift/polyphen output to transcript consequence summary.

Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

### CODE REVIEW

**Comment by ao508** [comment]
Related PR for java api client: https://github.com/genome-nexus/genome-nexus-java-api-client/pull/8

**Review by onursumer — APPROVED** [review]

**Review by sheridancbio — APPROVED** [review]
👍

**Comment by sheridancbio** [comment]
One issue I see is that there is a failing unit test (maybe integration?)
Please check nnotationIntegrationTest.testGenomicLocationSNVPOST and see if the expected output has changed @ao508

**Comment by ao508** [comment]
thanks! I will look into the failing integration test

**Pull request merged**
